### ISSUE TITLE
Error: No "exports" main defined in package.json

### ISSUE THREAD

**Issue by Soviut** [johannschopplich/pdfjs-serverless#3]
Node: v20.18.0
pdfjs-serverless: 0.6.0

I've used pdfjs-serverless in another project and it worked fine. However, when I installed it in a new project I got the following error. The previous project used pdfjs-serverless@0.4.2, but switching the new project to that version gave the same error.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/ian/projects/talint-match-middleware/node_modules/pdfjs-serverless/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at nextResolveSimple (/home/ian/projects/talint-match-middleware/node_modules/tsx/dist/register-DpmFHar1.cjs:3:942)
    at /home/ian/projects/talint-match-middleware/node_modules/tsx/dist/register-DpmFHar1.cjs:2:2550
    at /home/ian/projects/talint-match-middleware/node_modules/tsx/dist/register-DpmFHar1.cjs:2:1624
    at resolveTsPaths (/home/ian/projects/talint-match-middleware/node_modules/tsx/dist/register-DpmFHar1.cjs:3:760)
    at /home/ian/projects/talint-match-middleware/node_modules/tsx/dist/register-DpmFHar1.cjs:3:1038 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

**Comment by johannschopplich** [comment]
This package is ESM only. I'm not sure if converting the PDF.js bundle to CJS is a viable option. I would have to investigate.

Can you migrate your project to ESM? The ecosystem is slowly but steadily migrating from CJS to ESM, so I highly recommend following this approach. At least if your project allows it. 🙂

**Comment by Soviut** [comment]
Perhaps I just need to update my `tsconfig.json` to something other than

```json
"module": "commonjs"
```

**Comment by johannschopplich** [comment]
Yes, I recommend that.
